{% set name = "quickff" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/Q/QuickFF/QuickFF-{{ version }}.tar.gz
  sha256: 5d2458df1c7fe082df06125c024022ccf6a9c9b8bceb24d34cd438c014113d25

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - yaff
    - importlib_resources

test:
  imports:
    - quickff

about:
  home: https://github.com/molmod/QuickFF
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python code to quickly derive ab initio parameterized force fields.'

  description: |
    QuickFF is a pythonic code to easily derive fully flexible force fields from ab
    initio training data. The intended audience is very broad, one does not require
    much force field experience to generate reliable force fields for molecular
    systems.
  doc_url: http://molmod.github.io/QuickFF/
  dev_url: https://github.com/molmod/QuickFF

extra:
  recipe-maintainers:
    - jan-janssen
    - SanderBorgmans
